<a href="https://colab.research.google.com/github/Dinesh-Adhithya-H/Advanced-Programming-in-Python/blob/main/EECS_18097_Assignment_2_Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment 2 Part 1
### Due Date: 26 September 2021, Sunday, 11.00 am

### Example: Basic Numpy

(1) Create a NumPy array with the integers from your birthdate (year,
    month, and day)

(2) Retrieve the year.

(3) Replace the year with the current year.

(4) Create a NumPy array containing every 3rd number from 567 to 890. What is the 8th number in this array?  What is the 15th?

In [1]:
import numpy as np

In [2]:
# 1
a = np.array([1986, 12, 24])

In [3]:
# 2
a[0]

1986

In [4]:
# 3
a[0] = 2021

In [5]:
# 4
a= np.arange(567, 890, 3)
a

array([567, 570, 573, 576, 579, 582, 585, 588, 591, 594, 597, 600, 603,
       606, 609, 612, 615, 618, 621, 624, 627, 630, 633, 636, 639, 642,
       645, 648, 651, 654, 657, 660, 663, 666, 669, 672, 675, 678, 681,
       684, 687, 690, 693, 696, 699, 702, 705, 708, 711, 714, 717, 720,
       723, 726, 729, 732, 735, 738, 741, 744, 747, 750, 753, 756, 759,
       762, 765, 768, 771, 774, 777, 780, 783, 786, 789, 792, 795, 798,
       801, 804, 807, 810, 813, 816, 819, 822, 825, 828, 831, 834, 837,
       840, 843, 846, 849, 852, 855, 858, 861, 864, 867, 870, 873, 876,
       879, 882, 885, 888])

In [6]:
a[8]

591

In [7]:
a[15]

612

### Exercise 1 Basic Numpy

(1) Create an array of 10 random integers, from 0-100.

(2) Find the mean and standard deviation of these numbers.  

(3) Create another array of 10 random integers, from 0-100.

(4) Create a new array whose elements are the average of those from
    each of the previous ones.  

(5) Create an array of 10 random floats, from 0-100.

(6) We would expect the mean to be approaximately 50.  Is it?  What's
    the standard deviation?

(7) What are the min and max values?

In [8]:
random_array=np.random.randint(0,100,10)

In [9]:
random_array

array([78, 11, 86, 39, 54, 73,  8,  5, 44, 35])

In [10]:
np.mean(random_array),np.std(random_array)

(43.3, 28.050133689520983)

In [11]:
random_array1=np.random.randint(0,100,10)

In [12]:
average_array=np.array([np.mean(random_array),np.mean(random_array1)])

In [13]:
random_array2=np.random.random(10)*100

In [14]:
random_array2

array([33.52073857, 48.4878632 , 66.96522018, 73.64517455,  2.59131189,
       24.3247876 , 92.89982222, 87.11520724, 98.05437154, 31.35591156])

In [15]:
np.mean(random_array2),np.std(random_array2)

(55.89604085608458, 30.910662991927264)

In [16]:
np.max(random_array2),np.min(random_array2)

(98.05437154205545, 2.591311894664805)

### Exercise 2 Indexing

(1) Create an array of 20 random integers from 0 to 100.

(2) Find the largest even number.

(3) Find the mean of the odd numbers.

(4) Create a NumPy array from the first and last odd numbers.

(5) Create an array of 20 floats from 0-1,000.

(6) Find the items that are less than the mean.

(7) Find the items less than mean-std.

In [17]:
random_array3=np.random.randint(0,100,20)

In [18]:
random_array3

array([12, 45,  3, 48, 86, 80,  1, 43, 54, 81, 61, 32, 51, 98, 49, 27, 50,
       21, 43, 73])

In [20]:
filter=random_array3%2==0
np.max(random_array3[filter])

98

In [21]:
filter1=random_array3%2!=0
np.mean(random_array3[filter1])

41.5

In [23]:
np.array([random_array3[filter][0],random_array3[filter][-1]])

array([12, 50])

In [25]:
random_array4=np.random.rand(20)*1000

In [26]:
random_array4

array([885.36158308, 138.93505251, 650.18843116, 974.19703221,
       151.07393576, 290.62593673, 677.29781621, 612.26543675,
        91.72384163, 408.06971   , 797.99783568, 954.32223293,
       889.41921456, 772.58350368,  98.82750977, 382.96801078,
       828.09337073, 561.3012873 ,  78.22433893, 788.63764672])

In [27]:
filter2=random_array4<np.mean(random_array4)
random_array4[filter2]

array([138.93505251, 151.07393576, 290.62593673,  91.72384163,
       408.06971   ,  98.82750977, 382.96801078,  78.22433893])

In [28]:
filter3=random_array4<np.mean(random_array4)-np.std(random_array4)
random_array4[filter3]

array([138.93505251, 151.07393576,  91.72384163,  98.82750977,
        78.22433893])

### Exercise 3 More indexing

(1) Create a NumPy array of 20 random integers from 0-100.

(2) What's the smallest even number greater than the mean?

(3) Show all numbers either < mean-std OR > mean+std.

(4) Show odd numbers < mean and even numbers > mean.

In [36]:
random_array5=np.random.randint(0,100,20)
filter4=(random_array5>np.mean(random_array5)) & (random_array5%2==0)

In [37]:
np.min(random_array5[filter4])

54

In [50]:
filter5=np.logical_or((random_array5>np.mean(random_array5)-np.std(random_array5)) , (random_array5>np.mean(random_array5)+np.std(random_array5)))

In [51]:
random_array5[filter5]

array([73, 78, 54, 91, 63, 77, 36, 32, 21, 84, 89, 15, 99, 16, 32, 58])

In [47]:
filter6=np.logical_or(np.logical_and(random_array5<np.mean(random_array5) , random_array5%2!=0),np.logical_and(random_array5>np.mean(random_array5), random_array5%2==0))

In [49]:
np.mean(random_array5)

46.9

In [48]:
random_array5[filter6]

array([ 3, 78, 54, 21, 84,  7, 15,  3, 58,  7])

### Exercise 4 Assigning via indexes

(1) Create a NumPy array of 40 random integers, from 0-100.

(2) Find all numbers that are within 1 standard deviation of the mean,
    and set them to be equal to the mean.  Has the mean changed?  Has
    the std changed?

(3) Create another NumPy array of 10 random integers, from 0-100.

(4) Set the item at the even indexes to be equal to the items at the odd
    indexes.  So index 0 will get the value at index 1, etc.


In [57]:
random_array6=np.random.randint(0,100,40)

In [58]:
np.mean(random_array7),np.std(random_array7)

(52.0, 23.740261161158273)

In [59]:
filter7=np.logical_or(random_array6>np.mean(random_array6)-np.std(random_array6),random_array6<np.mean(random_array6)+np.std(random_array6))
random_array6[filter7]=np.mean(random_array6)

In [60]:
np.mean(random_array7),np.std(random_array7) # mean hasnt changed but std has changed

(52.0, 23.740261161158273)

In [64]:
random_array7=np.random.randint(0,100,10)

In [65]:
random_array7

array([23, 98,  5, 23, 29, 51, 56, 98,  5, 24])

In [66]:
for i in range(0,len(random_array7),2):
  random_array7[i]=random_array7[i+1]

In [67]:
random_array7

array([98, 98, 23, 23, 51, 51, 98, 98, 24, 24])

### Exercise 5 Data types

(1) Create a NumPy array of 10 random integers from 0-100.

(2) Calculate the mean, which will be a float.

(3) Create an array of type float based on it, and replace the
    outliers (i.e., <mean-std or >mean+std) with the mean.

(4) Create a NumPy array of 20 random floats from 0-100.

(5) Replace those numbers whose int portion is even with the mean.
    (So 20.5 would be replaced, but 21.5 would not be.)

In [68]:
random_array8=np.random.randint(0,100,10)
np.mean(random_array8)

45.3

In [70]:
import copy
random_array9=copy.deepcopy(random_array8)

In [73]:
random_array9[np.logical_and(random_array8>np.mean(random_array8)+np.std(random_array8),random_array8<np.mean(random_array8)-np.std(random_array8))]=np.mean(random_array8)

In [76]:
random_array.astype("int64")

array([78, 11, 86, 39, 54, 73,  8,  5, 44, 35])

In [80]:
random_array10=np.random.random(20)*100
random_array10[random_array10.astype("int64")%2==0]=np.mean(random_array10)

In [81]:
random_array10

array([47.11845522, 37.5767116 , 51.64951635, 51.64951635,  7.94533875,
       51.64951635, 51.64951635, 51.64951635, 53.9116516 , 51.64951635,
       95.02666881,  9.65833969,  9.04657691, 91.91926777, 51.64951635,
       51.64951635, 67.8437008 , 51.64951635, 51.64951635, 25.68910954])

### Exercise 6 nan

(1) Create a NumPy array of 30 random ints from 0-1000.

(2) Find the numbers that are <mean-std or >mean+std, and set them to
    be nan

(3) Now change those nan values to be the mean of the array's
    elements.

In [87]:
random_array11=np.random.randint(0,1000,30).astype("float")

In [88]:
random_array11[random_array11>np.mean(random_array11)+np.std(random_array11)]=np.nan

### Exercise 7 Multidimensional NumPy

(1) Create a 2-dimensional NumPy array of 45 random integers, from 0-100.

(2) Retrieve the elements at row index 2.

(3) Retrieve the elements at column index 3.

(4) Retrieve the elements at row indexes 1 and 4.

(5) Retrieve the elements at column indexes 1 and 4.

(6) Get the mean of the even numbers in row index 4.

(7) Get the mean of the odd numbers in column index 4.

In [91]:
multi_array=np.random.randint(0,100,(5,9))

In [92]:
multi_array[2]

array([91, 13, 27, 48, 13, 76, 87,  2, 44])

In [94]:
multi_array[:,3]

array([54, 54, 48, 79, 33])

In [97]:
multi_array[1:5]

array([[73, 10, 40, 54, 25,  3, 82, 93, 30],
       [91, 13, 27, 48, 13, 76, 87,  2, 44],
       [29, 55, 40, 79, 95, 76, 50, 43, 12],
       [62, 40, 94, 33,  5, 57, 30, 57, 24]])

In [95]:
multi_array[[1,4]]

array([[73, 10, 40, 54, 25,  3, 82, 93, 30],
       [62, 40, 94, 33,  5, 57, 30, 57, 24]])

In [101]:
multi_array[:,[1,4]]

array([[33, 92],
       [10, 25],
       [13, 13],
       [55, 95],
       [40,  5]])

In [106]:
np.mean(multi_array[:,4][multi_array[:,4]%2!=0])

34.5

In [107]:
np.mean(multi_array[4,:][multi_array[4,:]%2==0])

50.0

### Exercise 8 More Multidimensional

(1) Create a 6x6 NumPy array with random integers from 0-100.

(2) What is the mean of each column?

(3) Replace all even numbers in the array with twice their values. (So
    20 will become 40, and 40 will become 80.)

(4) Once again, calculate the mean of each column

(5) Now transpose the array and calculate the mean of each row.  Is it
    the same as you got before?

(6) Now sort each of the columns in the transposed array.  What does
    it look like now?

In [108]:
multi_array2=np.random.randint(0,100,(6,6))

In [113]:
np.mean(multi_array2,axis=0)

array([57.66666667, 55.66666667, 53.83333333, 68.33333333, 40.33333333,
       54.        ])

In [117]:
for i in range(6):
  for j in range(6):
    if multi_array2[i][j]%2==0:
      multi_array2[i][j]=multi_array2[i][j]*2

In [118]:
np.mean(multi_array2,axis=0)

array([91.        , 74.33333333, 78.5       , 68.33333333, 42.        ,
       75.33333333])

In [120]:
np.mean(np.transpose(multi_array2),axis=1)

array([91.        , 74.33333333, 78.5       , 68.33333333, 42.        ,
       75.33333333])

In [121]:
np.sort(np.transpose(multi_array2),axis=0)

array([[ 23,  37,  36,   0,  39,  11],
       [ 37,  65,  39,  15,  56,  20],
       [ 59,  80,  45,  37,  89,  36],
       [ 68,  87,  61,  81,  91,  37],
       [ 77,  91,  71,  99,  93, 104],
       [180, 120, 188, 156,  97, 152]])